release: Relase 1.0.1-RC2

diff --git a/dot_zshrc.d/functions/executable_common b/dot_zshrc.d/functions/executable_common
--- a/dot_zshrc.d/functions/executable_common
+++ b/dot_zshrc.d/functions/executable_common
@@ -1,9 +1,12 @@
 #!/bin/zsh
-
-function exist() {
-    command -v "$1" >/dev/null 2>&1
+####################################################################################################################################
+##########################              Common                ######################################################################
+##########################      https://dotfiles.download     ######################################################################
+####################################################################################################################################
+function exists() {
+  command -v "$1" >/dev/null 2>&1
 }
-function fn_exists() {
+function fun-exists() {
   whence -w $1 >/dev/null
 }
 function is-macos() { [[ "${OSTYPE}" == 'darwin'* ]]; }
@@ -14,78 +17,132 @@ function mkcd() {
   cd $@
 }
 
-function gclcd() {
-  git clone --recurse-submodules $@
-  cd "$(basename "$_" .git)"
-}
+# Required for $langinfo
+zmodload zsh/langinfo
 
-function most_used_commands() {
-  omz_history | awk '{print $2}' | sort | uniq -c | sort -nr | column -t |  nl | head -n40
-}
+# URL-encode a string
+#
+# Encodes a string using RFC 2396 URL-encoding (%-escaped).
+# See: https://www.ietf.org/rfc/rfc2396.txt
+#
+# By default, reserved characters and unreserved "mark" characters are
+# not escaped by this function. This allows the common usage of passing
+# an entire URL in, and encoding just special characters in it, with
+# the expectation that reserved and mark characters are used appropriately.
+# The -r and -m options turn on escaping of the reserved and mark characters,
+# respectively, which allows arbitrary strings to be fully escaped for
+# embedding inside URLs, where reserved characters might be misinterpreted.
+#
+# Prints the encoded string on stdout.
+# Returns nonzero if encoding failed.
+#
+# Usage:
+#  omz_urlencode [-r] [-m] [-P] <string> [<string> ...]
+#
+#    -r causes reserved characters (;/?:@&=+$,) to be escaped
+#
+#    -m causes "mark" characters (_.!~*''()-) to be escaped
+#
+#    -P causes spaces to be encoded as '%20' instead of '+'
+function omz_urlencode() {
+  emulate -L zsh
+  local -a opts
+  zparseopts -D -E -a opts r m P
 
-function mark() {
-  file="$HOME/.markfile"
-  [ -f $file ] || touch $file
-  if grep "^$1=" $file > /dev/null; then
-    sed -i -e "s:$1\=.*$:$1\=${PWD}:g" $file
-    echo "entry $1 changed"
-  else
-    echo "$1=$PWD" >> $file
-    echo "entry $1 added"
+  local in_str="$@"
+  local url_str=""
+  local spaces_as_plus
+  if [[ -z $opts[(r)-P] ]]; then spaces_as_plus=1; fi
+  local str="$in_str"
+
+  # URLs must use UTF-8 encoding; convert str to UTF-8 if required
+  local encoding=$langinfo[CODESET]
+  local safe_encodings
+  safe_encodings=(UTF-8 utf8 US-ASCII)
+  if [[ -z ${safe_encodings[(r)$encoding]} ]]; then
+    str=$(echo -E "$str" | iconv -f $encoding -t UTF-8)
+    if [[ $? != 0 ]]; then
+      echo "Error converting string from $encoding to UTF-8" >&2
+      return 1
+    fi
   fi
-}
 
-function goto() {
-  file="$HOME/.markfile"
-  if [ $# -eq 1 ]; then
-    dest=$(grep "^$1=" $file | cut -d= -f2)
-    cd $dest
-  else
-    echo "no mark specified"
+  # Use LC_CTYPE=C to process text byte-by-byte
+  local i byte ord LC_ALL=C
+  export LC_ALL
+  local reserved=';/?:@&=+$,'
+  local mark='_.!~*''()-'
+  local dont_escape="[A-Za-z0-9"
+  if [[ -z $opts[(r)-r] ]]; then
+    dont_escape+=$reserved
   fi
-}
-
-function chwd() {
-  mark WORKING_DIR
-  touch "$HOME/.wdfile"
-}
-
-function clwd() {
-  if [[ -f "$HOME/.wdfile" ]]; then
-    rm "$HOME/.wdfile"
+  # $mark must be last because of the "-"
+  if [[ -z $opts[(r)-m] ]]; then
+    dont_escape+=$mark
   fi
+  dont_escape+="]"
+
+  # Implemented to use a single printf call and avoid subshells in the loop,
+  # for performance (primarily on Windows).
+  local url_str=""
+  for (( i = 1; i <= ${#str}; ++i )); do
+    byte="$str[i]"
+    if [[ "$byte" =~ "$dont_escape" ]]; then
+      url_str+="$byte"
+    else
+      if [[ "$byte" == " " && -n $spaces_as_plus ]]; then
+        url_str+="+"
+      else
+        ord=$(( [##16] #byte ))
+        url_str+="%$ord"
+      fi
+    fi
+  done
+  echo -E "$url_str"
 }
 
-function gtwd() {
-  if [[ -f "$HOME/.wdfile" ]] && [ -z "$TMUX" ]; then
-    goto WORKING_DIR
+# URL-decode a string
+#
+# Decodes a RFC 2396 URL-encoded (%-escaped) string.
+# This decodes the '+' and '%' escapes in the input string, and leaves
+# other characters unchanged. Does not enforce that the input is a
+# valid URL-encoded string. This is a convenience to allow callers to
+# pass in a full URL or similar strings and decode them for human
+# presentation.
+#
+# Outputs the encoded string on stdout.
+# Returns nonzero if encoding failed.
+#
+# Usage:
+#   omz_urldecode <urlstring>  - prints decoded string followed by a newline
+function omz_urldecode {
+  emulate -L zsh
+  local encoded_url=$1
+
+  # Work bytewise, since URLs escape UTF-8 octets
+  local caller_encoding=$langinfo[CODESET]
+  local LC_ALL=C
+  export LC_ALL
+
+  # Change + back to ' '
+  local tmp=${encoded_url:gs/+/ /}
+  # Protect other escapes to pass through the printf unchanged
+  tmp=${tmp:gs/\\/\\\\/}
+  # Handle %-escapes by turning them into `\xXX` printf escapes
+  tmp=${tmp:gs/%/\\x/}
+  local decoded="$(printf -- "$tmp")"
+
+  # Now we have a UTF-8 encoded string in the variable. We need to re-encode
+  # it if caller is in a non-UTF-8 locale.
+  local -a safe_encodings
+  safe_encodings=(UTF-8 utf8 US-ASCII)
+  if [[ -z ${safe_encodings[(r)$caller_encoding]} ]]; then
+    decoded=$(echo -E "$decoded" | iconv -f UTF-8 -t $caller_encoding)
+    if [[ $? != 0 ]]; then
+      echo "Error converting string from UTF-8 to $caller_encoding" >&2
+      return 1
+    fi
   fi
-}
 
-function find-file() {
-  local FILE=$(fzf --preview-window=right:60% --preview='bat --color "always" {}')
-
-  if [ ! -z $FILE ]; then
-    $EDITOR $FILE
-  fi
-}
-
-function tre() {
-  local ignore_dirs=$(echo "$(cat .gitignore | sed '/^$/d' | sed '/^#/d' | sed '/[^/]$/d' | tr '\n' '|' | tr -d '/')renv|node_modules")
-  tree -I $ignore_dirs --dirsfirst $@
-}
-
-function history-all() {
-    history -E 1
-}
-
-# Cryptography
-function secret () {
-        output=~/"${1}".$(date +%s).enc
-        gpg --encrypt --armor --output ${output} -r $KEYID -r $EMAIL "${1}" && echo "${1} -> ${output}"
-}
-
-function reveal () {
-        output=$(echo "${1}" | rev | cut -c16- | rev)
-        gpg --decrypt --output ${output} "${1}" && echo "${1} -> ${output}"
+  echo -E "$decoded"
 }
